import { expect, test } from '@playwright/test'
import { auditPages, readStepIds } from './audit-pages'
import { CHEATSHEETS } from '../src/lib/cheatsheets'
import { STAGES } from '../src/lib/stages'

/**
 * Guards the derivation that replaced `audit.spec.ts`'s hand-written `PAGES`
 * list (TD-12).
 *
 * **What used to be here, and why it is gone.** This file opened with a
 * thirty-six-URL literal and an equivalence test: the derivation had to produce
 * exactly the list the hand-written array held on the day it was replaced. That
 * made the migration checkable, and it was the right test for the migration. It
 * proved that one event and nothing after it.
 *
 * Its own note said it had a shelf life and named the event that would end it —
 * stage 04 going `ready: true`, at which point the literal goes red for a
 * correct reason and the tempting fix is to paste in whatever the derivation
 * now emits. That edit would make the expectation generated by the thing it
 * checks, which is the defect class this repository has found seven times
 * (`docs/tracker.md`, Process observations). So the test and its array were
 * deleted rather than updated, on the instruction the note left. The array is
 * not kept "for reference" either: an unused 36-URL literal sitting beside a
 * derivation is an invitation to paste.
 *
 * **What remains, and what each piece can actually catch.** Read this before
 * trusting any of it — the three tests below guard three different things and
 * only one of them fails on a content change:
 *
 * - *stage coverage* asserts the swept stage set equals `STAGES.filter(s =>
 *   s.ready)`. Note what this does not do. `auditPages` walks that same filter,
 *   so against the current implementation the two sides cannot disagree; the
 *   test is a guard on `auditPages` itself, and it fails if that function ever
 *   stops deriving its stage list from the ready flag — a hardcoded list, an
 *   early return, a filter that drops one. Teeth-check it by mutating
 *   `audit-pages.ts`, never by flipping a `ready` flag, which fails through the
 *   throw below instead and proves a different test.
 * - *sheet coverage* is the same shape for `CHEATSHEETS`.
 * - *the empty-rail throw* is the one that catches a live, broken stage.
 */

test('the sweep covers exactly the stages marked ready, so a live stage cannot go unswept', async ({
  page,
}) => {
  const paths = await auditPages(page)

  const sweptStages = new Set(
    paths
      .filter((p) => p.startsWith('/stages/'))
      .map((p) => `/stages/${p.split('/')[2].split('#')[0]}`),
  )
  const expected = new Set(
    STAGES.filter((s) => s.ready).map((s) => `/stages/${s.slug}`),
  )

  expect([...sweptStages].sort()).toEqual([...expected].sort())
})

test('appends the reference index and every registered sheet, so a sheet added later cannot slip out of the sweep', async ({
  page,
}) => {
  const derived = await auditPages(page)
  const referencePages = derived.filter((url) => url.startsWith('/reference'))

  expect(referencePages).toEqual([
    '/reference',
    ...CHEATSHEETS.map((sheet) => `/reference/${sheet.slug}`),
  ])
})

test('refuses to sweep a stage that is ready but renders no steps, since silence there is the failure TD-12 describes', async ({
  page,
}) => {
  // Any stage that is `ready: false` and absent from `STAGE_CONTENT` renders
  // the "sheet not drawn" placeholder with no rail, which is the shape of the
  // bug: a stage flipped live before its content exists. `readStepIds` is
  // exported separately from `auditPages` so this can exercise the guard
  // against one stage without flipping a real `ready` flag.
  //
  // This used to name `04-project-setup`, which made it a second armed
  // tripwire beside the deleted literal — stage 04 going ready turns a stage
  // that must render nothing into one that renders fifteen steps, and the test
  // goes red having found no defect. It names `05-development` for no reason
  // beyond it being the next stage that is not built; when 05 is ported, move
  // this to whatever is still unbuilt rather than deleting it.
  await expect(readStepIds(page, '05-development')).rejects.toThrow(
    /renders no steps/,
  )
})
