import { expect, test } from '@playwright/test'
import { auditPages, readStepIds } from './audit-pages'
import { CHEATSHEETS } from '../src/lib/cheatsheets'

/**
 * Guards the derivation that replaced `audit.spec.ts`'s hand-written `PAGES`
 * list (TD-12).
 *
 * The list was maintained by hand for three stages: stage 02 added six hashes,
 * stage 03 added thirteen more as its reshape ran. Its failure mode was silent
 * — a stage could go `ready: true` and never be swept, and the suite would
 * still report green, because nothing compared the list against the stages
 * actually live.
 *
 * The assertion below is equivalence: derivation must produce exactly the
 * thirty-six URLs the hand-written list held on the day it was replaced. That
 * is what makes this a migration rather than a rewrite — a derivation that
 * silently swept fewer pages would otherwise look like a pass.
 *
 * These are deliberately spelled out rather than computed. Recomputing the
 * expectation from the same source the implementation reads would assert
 * nothing at all, which is the defect class this repository has now found
 * seven times (docs/tracker.md, Process observations).
 *
 * **This literal has a shelf life, and the next person to see it red is the
 * one this note is for.** It proves one migration. The moment a stage's ready
 * set changes — stage 04 is next — this test goes red for a correct reason,
 * and the tempting fix is to paste in whatever the derivation now emits. Do
 * not. From that edit on, the expectation is generated by the thing it checks,
 * which is precisely what the paragraph above says it must never be.
 *
 * **Delete this test and its array instead**, and if you want the coverage it
 * was holding, assert stage coverage rather than exact URLs: the set of stage
 * paths in the derived list should equal `STAGES.filter(s => s.ready)` mapped
 * to `/stages/<slug>`. That re-reads `STAGES`, but it checks the *filter* did
 * its job rather than checking step ids against themselves, so it is not
 * circular in the way this note warns about — and it catches a dropped stage,
 * which is the one thing nothing else here would notice. Recorded as TD-36.
 */

const PAGES_AS_HAND_WRITTEN = [
  '/',
  '/stages/01-product-discovery#frame',
  '/stages/01-product-discovery#research',
  '/stages/01-product-discovery#ai',
  '/stages/01-product-discovery#talk',
  '/stages/01-product-discovery#decide',
  '/stages/01-product-discovery#record',
  '/stages/02-planning#done',
  '/stages/02-planning#cut',
  '/stages/02-planning#sequence',
  '/stages/02-planning#size',
  '/stages/02-planning#ai',
  '/stages/02-planning#write',
  '/stages/02-planning#horizon',
  '/stages/03-architecture#reverse',
  '/stages/03-architecture#require',
  '/stages/03-architecture#trace',
  '/stages/03-architecture#model',
  '/stages/03-architecture#worksheet',
  '/stages/03-architecture#shape',
  '/stages/03-architecture#oneapp',
  '/stages/03-architecture#boundaries',
  '/stages/03-architecture#sketch',
  '/stages/03-architecture#flow',
  '/stages/03-architecture#resilience',
  '/stages/03-architecture#schema',
  '/stages/03-architecture#indexes',
  '/stages/03-architecture#tenancy',
  '/stages/03-architecture#concurrency',
  '/stages/03-architecture#races',
  '/stages/03-architecture#evolve',
  '/stages/03-architecture#contract',
  '/stages/03-architecture#access',
  '/stages/03-architecture#record',
  '/stages/03-architecture#ai',
  '/stages/03-architecture#traps',
]

test('derives exactly the pages the hand-written list held, since a derivation that swept fewer would still look green', async ({
  page,
}) => {
  const derived = await auditPages(page)

  // The reference sheets are appended after the stage sweep and were never in
  // the hand-written list, so they are excluded here rather than added to the
  // fixture above. Padding the fixture would quietly turn this from a migration
  // guard into a restatement of whatever the deriver currently returns, which is
  // the one thing its docblock says it must not become.
  const stagePages = derived.filter((url) => !url.startsWith('/reference'))

  // Order matters as much as membership: the sweep walks stages in `STAGES`
  // order, and a derivation that returned the right set in the wrong order
  // would mean it is reading something other than the rail.
  expect(stagePages).toEqual(PAGES_AS_HAND_WRITTEN)
})

test('appends the reference index and every registered sheet, so a sheet added later cannot slip out of the sweep', async ({
  page,
}) => {
  const derived = await auditPages(page)
  const referencePages = derived.filter((url) => url.startsWith('/reference'))

  expect(referencePages).toEqual([
    '/reference',
    ...CHEATSHEETS.map((sheet) => `/reference/${sheet.slug}`),
  ])
})

test('refuses to sweep a stage that is ready but renders no steps, since silence there is the failure TD-12 describes', async ({
  page,
}) => {
  // `04-project-setup` is `ready: false` and absent from `STAGE_CONTENT`, so
  // its route renders the "sheet not drawn" placeholder with no rail. Asking
  // the deriver to read steps from it is the shape of the bug: a stage flipped
  // live before its content exists.
  // `readStepIds` is exported separately from `auditPages` so this can exercise
  // the guard against one stage without flipping a real `ready` flag.
  await expect(readStepIds(page, '04-project-setup')).rejects.toThrow(
    /renders no steps/,
  )
})
