import { expect, test } from '@playwright/test'
import { auditPages, readStepIds } from './audit-pages'
import { CHEATSHEETS } from '../src/lib/cheatsheets'
import { STEP_IDS_BY_SLUG } from '../src/features/step-ids'

/**
 * Guards the derivation that replaced `audit.spec.ts`'s hand-written `PAGES`
 * list (TD-12).
 *
 * **What used to be here, and why it is gone.** This file opened with a
 * thirty-six-URL literal and an equivalence test: the derivation had to produce
 * exactly the list the hand-written array held on the day it was replaced. That
 * made the migration checkable, and it was the right test for the migration. It
 * proved that one event and nothing after it.
 *
 * Its own note said it had a shelf life and named the event that would end it —
 * stage 04 going `ready: true`, at which point the literal goes red for a
 * correct reason and the tempting fix is to paste in whatever the derivation
 * now emits. That edit would make the expectation generated by the thing it
 * checks, which is the defect class this repository has found seven times
 * (`docs/tracker.md`, Process observations). So the test and its array were
 * deleted rather than updated, on the instruction the note left. The array is
 * not kept "for reference" either: an unused 36-URL literal sitting beside a
 * derivation is an invitation to paste.
 *
 * **What replaced it, and why not the obvious thing.** The first replacement
 * asserted that the swept stage *set* equalled `STAGES.filter(s => s.ready)`.
 * A review killed it, correctly: `auditPages` walks that same filter, so the
 * two sides cannot disagree and the assertion could only go red if
 * `audit-pages.ts` were edited — a test named for a guarantee it did not hold.
 * It also replaced one URL per step with one entry per stage, quietly dropping
 * the only thing in the suite that would notice `readStepIds` returning *some*
 * of a rail.
 *
 * What is below instead compares an observation to a declaration, which is the
 * one pairing available here that is not a source checked against itself:
 * `auditPages` reads the rail out of the real built app, and
 * `STEP_IDS_BY_SLUG` is what the stages say they contain. Neither is derived
 * from the other. A stage that goes unswept fails it, a step that disappears
 * fails it, and a selector that half-works fails it.
 *
 * `features/rails.test.tsx` makes the same comparison in jsdom against the
 * component. Both are worth having: that one runs in the unit gate and fails
 * in seconds, this one is the only check that the *built* app agrees.
 */

test('the sweep reaches every step every built stage declares, since a selector that returned half a rail would shrink it in silence', async ({
  page,
}) => {
  const swept = (await auditPages(page)).filter((p) => p.startsWith('/stages/'))

  const declared = Object.entries(STEP_IDS_BY_SLUG).flatMap(([slug, ids]) =>
    ids.map((id) => `/stages/${slug}#${id}`),
  )

  // Sorted rather than compared in place: rail order is `rails.test.tsx`'s
  // claim, and asserting it twice would mean a re-cut seam reddens two suites
  // for one reason.
  expect([...swept].sort()).toEqual([...declared].sort())
})

test('appends the reference index and every registered sheet, so a sheet added later cannot slip out of the sweep', async ({
  page,
}) => {
  const derived = await auditPages(page)
  const referencePages = derived.filter((url) => url.startsWith('/reference'))

  expect(referencePages).toEqual([
    '/reference',
    ...CHEATSHEETS.map((sheet) => `/reference/${sheet.slug}`),
  ])
})

test('refuses to sweep a stage that is ready but renders no steps, since silence there is the failure TD-12 describes', async ({
  page,
}) => {
  // Any stage that is `ready: false` and absent from `STAGE_CONTENT` renders
  // the "sheet not drawn" placeholder with no rail, which is the shape of the
  // bug: a stage flipped live before its content exists. `readStepIds` is
  // exported separately from `auditPages` so this can exercise the guard
  // against one stage without flipping a real `ready` flag.
  //
  // This used to name `04-project-setup`, which made it a second armed
  // tripwire beside the deleted literal — stage 04 going ready turns a stage
  // that must render nothing into one that renders fifteen steps, and the test
  // goes red having found no defect. It names `05-development` for no reason
  // beyond it being the next stage that is not built; when 05 is ported, move
  // this to whatever is still unbuilt rather than deleting it.
  await expect(readStepIds(page, '05-development')).rejects.toThrow(
    /renders no steps/,
  )
})
