import { highlightTs } from '@/lib/highlight'
import { CHEATSHEETS } from './index'

/**
 * Renders `highlighted.generated.ts`, keyed by the plain-text `code` each
 * entry was highlighted from — regenerated with `pnpm gen:highlighted`
 * (`generate-highlighted.test.ts` runs this and checks it against the
 * committed file, the identical arrangement `render.ts`/`cheatsheets.md` and
 * `terms.ts`/`glossary.md` already use).
 *
 * **Why generated rather than highlighted where the data is declared.** The
 * first attempt called Shiki via a top-level `await` inside
 * `solid-principles.ts` itself. Vitest and `next build` both resolve that
 * fine — but Playwright's own test transform does not support top-level
 * await, and `e2e/audit-pages.ts` imports this registry directly. `pnpm test`
 * and `pnpm build` both stayed green while `pnpm test:e2e` failed outright,
 * which is exactly the shape of bug this project's own audit-pages
 * derivation exists to prevent for *pages* — this is the same failure mode
 * one level down, in the data a page is built from. Precomputing here keeps
 * every consumer, including the data modules themselves, fully synchronous.
 */
export async function renderHighlighted(): Promise<string> {
  const codes = new Set<string>()
  for (const sheet of CHEATSHEETS) {
    for (const section of sheet.sections) {
      for (const row of section.rows) {
        for (const ex of row.example ?? []) codes.add(ex.code)
      }
    }
  }

  const entries = await Promise.all(
    [...codes]
      .sort()
      .map(async (code) => [code, await highlightTs(code)] as const),
  )
  const map = Object.fromEntries(entries)

  return `// Generated by src/lib/cheatsheets/generate-highlighted.ts via \`pnpm gen:highlighted\`.
// Do not hand-edit — see that file's docblock for why this exists instead of
// highlighting at import time.
export const highlightedHtml: Record<string, string> = ${JSON.stringify(map, null, 2)}
`
}
